# Generated by Django 3.1.5 on 2021-02-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('charity_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('charity', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('charity_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('username', models.EmailField(max_length=254)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APITest.item')),
            ],
        ),
    ]
